package com.colofabrix.scala.beesight.config

final case class DetectionConfig(
  TakeoffSpeedThreshold: Double,
  TakeoffClimbRate: Double,
  TakeoffMaxAltitude: Double,
  TakeoffBacktrackWindow: Int,
  TakeoffValidationWindow: Int,
  FreefallVerticalSpeedThreshold: Double,
  FreefallAccelThreshold: Double,
  FreefallAccelMinVelocity: Double,
  FreefallMinAltitudeAbove: Double,
  FreefallMinAltitudeAbsolute: Double,
  FreefallBacktrackWindow: Int,
  FreefallValidationWindow: Int,
  CanopyVerticalSpeedMax: Double,
  CanopyBacktrackWindow: Int,
  CanopyValidationWindow: Int,
  LandingSpeedMax: Double,
  LandingStabilityThreshold: Double,
  LandingMeanVerticalSpeedMax: Double,
  LandingAltitudeTolerance: Double,
  LandingStabilityWindowSize: Int,
  LandingBacktrackWindow: Int,
  LandingValidationWindow: Int,
  ClipAcceleration: Double,
  SmoothingVerticalSpeedWindowSize: Int,
  BacktrackVerticalSpeedWindowSize: Int,
)

object DetectionConfig {

  val default: DetectionConfig =
    DetectionConfig(
      TakeoffSpeedThreshold = 25.0,
      TakeoffClimbRate = -1.0,
      TakeoffMaxAltitude = 600.0,
      TakeoffBacktrackWindow = 10,
      TakeoffValidationWindow = 40,
      FreefallVerticalSpeedThreshold = 25.0,
      FreefallAccelThreshold = 3.0,
      FreefallAccelMinVelocity = 10.0,
      FreefallMinAltitudeAbove = 600.0,
      FreefallMinAltitudeAbsolute = 600.0,
      FreefallBacktrackWindow = 10,
      FreefallValidationWindow = 40,
      CanopyVerticalSpeedMax = 12.0,
      CanopyBacktrackWindow = 10,
      CanopyValidationWindow = 40,
      LandingSpeedMax = 3.0,
      LandingStabilityThreshold = 0.5,
      LandingMeanVerticalSpeedMax = 1.0,
      LandingAltitudeTolerance = 500.0,
      LandingStabilityWindowSize = 10,
      LandingBacktrackWindow = 10,
      LandingValidationWindow = 40,
      ClipAcceleration = 20.0,
      SmoothingVerticalSpeedWindowSize = 5,
      BacktrackVerticalSpeedWindowSize = 10,
    )
}
